Description of example
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > examples > example.m
example
PURPOSE
TTeMPS Toolbox.
SYNOPSIS
This is a script file.
DESCRIPTION
   TTeMPS Toolbox.
   Michael Steinlechner, 2013-2016
   Questions and contact: michael.steinlechner@epfl.ch
   BSD 2-clause license, see LICENSE.txt
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP Display TT/MPS tensor.
innerprod INNERPROD Inner product between two TT/MPS tensors.
orthogonalize ORTHOGONALIZE Orthogonalize tensor.
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
truncate TRUNCATE Truncate TTeMPS tensor to prescribed rank.
disp DISP Display TT/MPS block-mu tensor.
innerprod INNERPROD Inner product between two TT/MPS tensors.
orthogonalize ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
truncate ROUND Approximate TTeMPS tensor within a prescribed tolerance.
disp DISP Display TT/MPS operator.
round ROUND Approximate TTeMPS operator within a prescribed tolerance.
disp DISP Display TT/MPS operator.
TTeMPS_rand TTEMPS_RAND Create random TTeMPS tensor
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
This function is called by:
SOURCE CODE
%   TTeMPS Toolbox.
%   Michael Steinlechner, 2013-2016
%   Questions and contact: michael.steinlechner@epfl.ch
%   BSD 2-clause license, see LICENSE.txt
rng(11);
disp('Number of dimensions:')
d = 5
disp('Define tensor size:')
n = [7 8 9 10 11]
disp('Define rank vector (note that in the TT/MPS format, both the first and last rank are 1):')
r = [1 4 5 6 7 1]
disp('Create two random TT/MPS tensors:')
X = TTeMPS_rand(r, n)
Y = TTeMPS_rand(r, n)
disp('Calculate inner product between them:')
ip = innerprod(X, Y)
disp('Left-orthogonalize X:')
X = orthogonalize(X, 1)
disp('Right-orthogonalize Y:')
Y = orthogonalize(Y, Y.order)
disp('Add X and Y')
Z = X + Y
disp('Truncate Z back to rank r:')
Z_trunc = truncate(Z, r)
disp('Note that we also have the round() operations,')
disp('where you specify a desired accuracy instead of prescribed rank')
Z_round = round(Z, 1e-2)