Description of TTeMPS_op_to_TTeMPS
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS_op > TTeMPS_op_to_TTeMPS.m
TTeMPS_op_to_TTeMPS
PURPOSE
TTeMPS_op_to_TTeMPS Convert to TT Toolbox matrix format.
SYNOPSIS
function B = TTeMPS_op_to_TTeMPS(A)
DESCRIPTION
TTeMPS_op_to_TTeMPS Convert to TT Toolbox matrix format.
   TT = TTeMPS_op_to_TTeMPS( A ) takes the TTeMPS operator A and converts it into
   a TTeMPS object by reshaping.
   See also TTeMPS_op_to_TT_matrix
CROSS-REFERENCE INFORMATION
This function calls:
TTeMPS
This function is called by:
TTeMPS_op
full FULL Convert TTeMPS_op operator to full array
SOURCE CODE
function B = TTeMPS_op_to_TTeMPS(A)
    %TTeMPS_op_to_TTeMPS Convert to TT Toolbox matrix format.
    %   TT = TTeMPS_op_to_TTeMPS( A ) takes the TTeMPS operator A and converts it into
    %   a TTeMPS object by reshaping.
    %
    %   See also TTeMPS_op_to_TT_matrix
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    U = cellfun(@(y) reshape(y, [size(y,1), size(y,2)*size(y,3), size(y,4)]), ...
                        A.U, 'UniformOutput', false);
    B = TTeMPS( U );
end