Description of matricize
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > matricize.m
matricize
PURPOSE
MATRICIZE Matricize 3D Matlab array.
SYNOPSIS
function res = matricize(U, mode)
DESCRIPTION
MATRICIZE Matricize 3D Matlab array.
   A = MATRICIZE(U, MODE) matricizes the 3D Matlab array U along the
   specified mode MODE. Higher dimensions than 3 are not supported.
   See also TENSORIZE, TENSORPROD_TTEMPS, UNFOLD.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
skewsymmetricfactory Returns a manifold struct to optimize over k skew-symmetric matrices of size n
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
apply APPLY Application of TT/MPS operator to a TT/MPS tensor
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS operator.
apply APPLY Application of TT/MPS Laplace-like operator to a TT/MPS tensor
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS Laplace operator.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
precond_laplace_noSaddle TTeMPS Toolbox.
precond_laplace_noorth TTeMPS Toolbox.
precond_laplace_overlapGS TTeMPS Toolbox.
precond_laplace_overlapJacobi TTeMPS Toolbox.
precond_rankOne TTeMPS Toolbox.
TTeMPS_op_NN
TTeMPS_op_NN_hermite
anisotropicdiffusion
newton_potential
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
SOURCE CODE
function res = matricize(U, mode)
    %MATRICIZE Matricize 3D Matlab array.
    %   A = MATRICIZE(U, MODE) matricizes the 3D Matlab array U along the
    %   specified mode MODE. Higher dimensions than 3 are not supported.
    %
    %   See also TENSORIZE, TENSORPROD_TTEMPS, UNFOLD.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    d = size(U);
    % pad with 1 for the last dim (annoying)
    if length(d) == 2
        d = [d, 1];
    end
    switch mode
        case 1
            res = reshape( U, [d(1), d(2)*d(3)] );
        case 2
            res = reshape( permute( U, [2, 1, 3]), [d(2), d(1)*d(3)] );
        case 3
            res = transpose( reshape( U, [d(1)*d(2), d(3)] ) );
        otherwise
            error('Invalid mode input in function matricize')
    end
end