Description of tensorize
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > tensorize.m
tensorize
PURPOSE
TENSORIZE Tensorize matrix (inverse matricization).
SYNOPSIS
function res = tensorize(U, mode, d)
DESCRIPTION
TENSORIZE Tensorize matrix (inverse matricization).
   X = TENSORIZE(U, MODE, D) (re-)tensorizes the matrix U along the
   specified mode MODE into a tensor X of size D(1) x D(2) x D(3). Higher
   dimensions than 3 are not supported. Tensorize is inverse matricization,
   that is, X == tensorize( matricize(X, i), i, size(X)) for all modes i.
   See also MATRICIZE, TENSORPROD_TTEMPS, UNFOLD.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
precond_laplace_noSaddle TTeMPS Toolbox.
precond_laplace_noorth TTeMPS Toolbox.
precond_laplace_overlapGS TTeMPS Toolbox.
precond_laplace_overlapJacobi TTeMPS Toolbox.
precond_rankOne TTeMPS Toolbox.
TTeMPS_op_NN
TTeMPS_op_NN_hermite
anisotropicdiffusion
newton_potential
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
SOURCE CODE
function res = tensorize(U, mode, d)
    %TENSORIZE Tensorize matrix (inverse matricization).
    %   X = TENSORIZE(U, MODE, D) (re-)tensorizes the matrix U along the
    %   specified mode MODE into a tensor X of size D(1) x D(2) x D(3). Higher
    %   dimensions than 3 are not supported. Tensorize is inverse matricization,
    %   that is, X == tensorize( matricize(X, i), i, size(X)) for all modes i.
    %
    %   See also MATRICIZE, TENSORPROD_TTEMPS, UNFOLD.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    % pad with 1 for the last dim (annoying)
    if length(d) == 2
        d = [d, 1];
    end
    switch mode
        case 1
            res = reshape( U, d );
        case 2
            res = ipermute( reshape(U, [d(2), d(1), d(3)]), [2, 1, 3] );
        case 3
            res = reshape( transpose(U), d );
        otherwise
            error('Invalid mode input in function matricize')
    end
end