Description of tensorprod_ttemps
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > tensorprod_ttemps.m
tensorprod_ttemps
PURPOSE
TENSORPROD_TTEMPS Tensor-times-Matrix product.
SYNOPSIS
function res = tensorprod_ttemps(U, A, mode, apply_inv)
DESCRIPTION
TENSORPROD_TTEMPS Tensor-times-Matrix product.
   A = TENSORPROD_TTEMPS(U, A, MODE) performs the mode-MODE product between the
   tensor U and matrix A. Higher dimensions than 3 are not supported.
   A = TENSORPROD_TTEMPS(U, A, MODE, TRUE) multiplies with A^{-1} instead of A.
   Renamed from tensorprod to tensorprod on April 20, 2022 to accomodate the new
   Matlab built-in function tensorprod in R2022a.
   See also MATRICIZE, TENSORIZE, UNFOLD.
CROSS-REFERENCE INFORMATION
This function calls:
matricize MATRICIZE Matricize 3D Matlab array.
tensorize TENSORIZE Tensorize matrix (inverse matricization).
This function is called by:
TT_weingarten Weingarten map computation for the fixed TT-rank manifold.
contract CONTRACT Contraction of two TT/MPS tensors.
innerprod INNERPROD Inner product between two TT/MPS tensors.
orth_at ORTH_AT Orthogonalize single core.
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
truncate TRUNCATE Truncate TTeMPS tensor to prescribed rank.
innerprod INNERPROD Inner product between two TT/MPS tensors.
shift TTeMPS Toolbox.
constr_precond_inner TTeMPS Toolbox.
TTeMPS_tangent
TTeMPS_tangent_orth
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
precond_laplace_noorth TTeMPS Toolbox.
precond_laplace_overlapGS TTeMPS Toolbox.
precond_laplace_overlapJacobi TTeMPS Toolbox.
precond_rankOne TTeMPS Toolbox.
SOURCE CODE
function res = tensorprod_ttemps(U, A, mode, apply_inv)
    %TENSORPROD_TTEMPS Tensor-times-Matrix product.
    %   A = TENSORPROD_TTEMPS(U, A, MODE) performs the mode-MODE product between the
    %   tensor U and matrix A. Higher dimensions than 3 are not supported.
    %
    %   A = TENSORPROD_TTEMPS(U, A, MODE, TRUE) multiplies with A^{-1} instead of A.
    %
    %   Renamed from tensorprod to tensorprod on April 20, 2022 to accomodate the new
    %   Matlab built-in function tensorprod in R2022a.
    %
    %   See also MATRICIZE, TENSORIZE, UNFOLD.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    if nargin==3
        apply_inv = false;
    end
    d = size(U);
    % pad with 1 for the last dim (annoying)
    if length(d) == 2
        d = [d, 1];
    end
    d(mode) = size(A,1);
    if apply_inv
        res = A \ matricize( U, mode );
        res = tensorize( res, mode, d );
    else
        res = A * matricize( U, mode );
        res = tensorize( res, mode, d );
    end
end