Description of trunc_singular
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > trunc_singular.m
trunc_singular
PURPOSE
REL_TRUNC_SINGULAR Helper routine to truncate singular values
SYNOPSIS
function s = trunc_singular(s, tol, relative, maxrank)
DESCRIPTION
 REL_TRUNC_SINGULAR Helper routine to truncate singular values
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
from_array FROM_ARRAY Approximate full array by TTeMPS tensor of prescribed rank
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
splitcore SPLITCORE Merging of two cores of a TT/MPS tensor.
shift TTeMPS Toolbox.
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
SOURCE CODE
function s = trunc_singular(s, tol, relative, maxrank)
% REL_TRUNC_SINGULAR Helper routine to truncate singular values
%   TTeMPS Toolbox.
%   Michael Steinlechner, 2013-2016
%   Questions and contact: michael.steinlechner@epfl.ch
%   BSD 2-clause license, see LICENSE.txt
    if ~exist('relative','var'),    relative = true;     end
    if ~exist('maxrank','var'), maxrank = length(s); end
    summ = cumsum(s.^2,'reverse');
    if relative
        s = find(summ > tol^2, 1, 'last');
        if isempty(s), s = 1; end
    else
        s = find(summ > tol^2*summ(1), 1, 'last');
        if isempty(s), s = 1; end
    end
    s = min([s, maxrank, length(s)]);
end