Description of TTeMPS_rand
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > TTeMPS_rand.m
TTeMPS_rand
PURPOSE
TTEMPS_RAND Create random TTeMPS tensor
SYNOPSIS
function x = TTeMPS_rand(r, n)
DESCRIPTION
 TTEMPS_RAND Create random TTeMPS tensor
   X = TTEMPS_RAND(R, N) creates a length(N)-dimensional TTeMPS tensor
   of size N(1)*N(2)*...N(end) with ranks R by filling the cores with
   iid uniform random numbers in [0, 1].
   Note that the first and last entry of the rank vector must be 1.
CROSS-REFERENCE INFORMATION
This function calls:
TTeMPS
This function is called by:
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
ex_completion_compare_als_riemann This example shows a simple comparison of two different algorithm for tensor completion:
ex_completion_rankadaptive Example script for RANK-ADAPTIVE TENSOR COMPLETION, see Algorithm RTTC described in
example TTeMPS Toolbox.
linearsystem_compare Example code for the algorithms described in
SOURCE CODE
function x = TTeMPS_rand(r, n)
% TTEMPS_RAND Create random TTeMPS tensor
%   X = TTEMPS_RAND(R, N) creates a length(N)-dimensional TTeMPS tensor
%   of size N(1)*N(2)*...N(end) with ranks R by filling the cores with
%   iid uniform random numbers in [0, 1].
%   Note that the first and last entry of the rank vector must be 1.
%
%   TTeMPS Toolbox.
%   Michael Steinlechner, 2013-2016
%   Questions and contact: michael.steinlechner@epfl.ch
%   BSD 2-clause license, see LICENSE.txt
    if length(r) ~= length(n)+1
        error('Size mismatch in arguments')
    end
    U = cell(1, length(n));
    for i = 1:length(n)
        U{i} = rand(r(i), n(i), r(i+1));
    end
    x = TTeMPS(U);
end