Description of unfold
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > unfold.m
unfold
PURPOSE
UNFOLD Left/right-unfold a 3D array.
SYNOPSIS
function W = unfold(U, dir)
DESCRIPTION
UNFOLD Left/right-unfold a 3D array.
   W = UNFOLD(U, DIR) unfolds the 3-dim. tensor U in direction DIR, where
   DIR is either 'LEFT' or 'RIGHT' (case insensitive).
   See also MATRICIZE, TENSORIZE, TENSORPROD_TTEMPS.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
TT_weingarten Weingarten map computation for the fixed TT-rank manifold.
full FULL Convert TTeMPS tensor to full array
innerprod INNERPROD Inner product between two TT/MPS tensors.
mergecore MERGECORE Merging of two cores of a TT/MPS tensor.
orth_at ORTH_AT Orthogonalize single core.
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
subsref SUBSREF Subscripted reference for TTeMPS.
truncate TRUNCATE Truncate TTeMPS tensor to prescribed rank.
full FULL Convert TTeMPS tensor to full array
innerprod INNERPROD Inner product between two TT/MPS tensors.
TTeMPS_tangent
TTeMPS_tangent_orth
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
increaseRank_mod Rank-1 gradient approximation to increase the rank.
alsLinsolve_rankOne TTeMPS Toolbox.
amen TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
check_precond_laplace TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
precond_laplace_noSaddle TTeMPS Toolbox.
precond_laplace_overlapJacobi TTeMPS Toolbox.
precond_rankOne TTeMPS Toolbox.
fixedTTrankfactory Manifold of tensors of fixed Tensor Train (TT) rank, embedded geometry
SOURCE CODE
function W = unfold(U, dir)
    %UNFOLD Left/right-unfold a 3D array.
    %   W = UNFOLD(U, DIR) unfolds the 3-dim. tensor U in direction DIR, where
    %   DIR is either 'LEFT' or 'RIGHT' (case insensitive).
    %
    %   See also MATRICIZE, TENSORIZE, TENSORPROD_TTEMPS.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    d = size(U);
    % pad with 1 for the last dim (annoying)
    if length(size(U)) == 2
        d = [d, 1];
    end
    if strcmpi(dir, 'left')
        W = reshape( U, [d(1)*d(2), d(3)] );
    elseif strcmpi(dir, 'right')
        W = reshape( U, [d(1), d(2)*d(3)] );
    else
        error('Unknown direction specified. Choose either LEFT or RIGHT')
    end
end