Description of display
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > display.m
display
PURPOSE
DISP Display TT/MPS tensor as a tensor network
SYNOPSIS
function display(x)
DESCRIPTION
DISP Display TT/MPS tensor as a tensor network
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP Display TT/MPS tensor.
disp DISP Display TT/MPS block-mu tensor.
disp DISP Display TT/MPS operator.
disp DISP Display TT/MPS operator.
This function is called by:
TTeMPS
TTeMPS_block
TTeMPS_op
TTeMPS_op_laplace
SOURCE CODE
function display(x)
    %DISP Display TT/MPS tensor as a tensor network
    %
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    disp( x, inputname(1));
end