Description of left_orth_with_gauge
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > left_orth_with_gauge.m
left_orth_with_gauge
PURPOSE
LEFT_ORTH_WITH_GAUGE Left orthogonalization with storage of gauge matrices
SYNOPSIS
function [xL, G] = left_orth_with_gauge(xR)
DESCRIPTION
 LEFT_ORTH_WITH_GAUGE Left orthogonalization with storage of gauge matrices
 Given a right orthogonal X, compute a left orthogonalization and keep
 the gauge matrices that relates them.
  The i-th core of xR
       unfold(xR.U{i},'left')
  is equal to the transformed i-th core of xL
       kron(eye(n(i)),inv(G{i-1}))*unfold(xL.U{i},'left')*G{i}
  (where fore i=1 and i=d, G{i} = 1).
  Or, equivalently
       tensorprod( tensorprod( xL.U{i}, G{i}', 3), inv(G{i-1}), 1)
  equals
       xR.U{i}.
   See also GAUGE_MATRICES
CROSS-REFERENCE INFORMATION
This function calls:
orth_at ORTH_AT Orthogonalize single core.
This function is called by:
gauge_matrices GAUGE_MATRICES Right and left orthogonalization with storage of gauge matrices
RiemannLinsolve Riemannian approx. Newton for linear systems. For more information, we refer to the report
RiemannPrecondSteep TTeMPS Toolbox.
SOURCE CODE
function [xL, G] = left_orth_with_gauge(xR)
% LEFT_ORTH_WITH_GAUGE Left orthogonalization with storage of gauge matrices
%
% Given a right orthogonal X, compute a left orthogonalization and keep
% the gauge matrices that relates them.
%
%  The i-th core of xR
%       unfold(xR.U{i},'left')
%  is equal to the transformed i-th core of xL
%       kron(eye(n(i)),inv(G{i-1}))*unfold(xL.U{i},'left')*G{i}
%  (where fore i=1 and i=d, G{i} = 1).
%
%  Or, equivalently
%       tensorprod(tensorprod(xL.U{i}, G{i}', 3), inv(G{i-1}), 1)
%  equals
%       xR.U{i}.
%
%   See also GAUGE_MATRICES
%   TTeMPS Toolbox.
%   Michael Steinlechner, 2013-2016
%   Questions and contact: michael.steinlechner@epfl.ch
%   BSD 2-clause license, see LICENSE.txt
    xL = xR;
    G = cell(xR.order-1, 1);
    % left orthogonalization till pos (from left)
    for i = 1:xR.order-1
        [xL, G{i}] = orth_at( xL, i, 'left' );
    end
end