Description of minus
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > minus.m
minus
PURPOSE
MINUS Substraction of two TT/MPS tensors.
SYNOPSIS
function z = minus(x, y)
DESCRIPTION
MINUS Substraction of two TT/MPS tensors.
   Z = MINUS(X,Y) substracts two TT/MPS tensors. The rank of the resulting
   tensor is the sum of the individual ranks.
   See also PLUS, UMINUS.
CROSS-REFERENCE INFORMATION
This function calls:
plus PLUS Addition of two TT/MPS tensors.
uminus UMINUS Unary minus.
plus PLUS Addition of two TT/MPS block-mu tensors.
uminus UMINUS Unary minus.
plus PLUS Addition of two TT/MPS operators.
This function is called by:
shapefit_smoothed ShapeFit formulation for sensor network localization from pair directions
centeredmatrixfactory Linear manifold struct. for optimization over matrices with centered cols
shapefitfactory Linear manifold structure for optimization over the ShapeFit search space
TTeMPS
TTeMPS_block
TTeMPS_tangent_orth
SOURCE CODE
function z = minus(x, y)
    %MINUS Substraction of two TT/MPS tensors.
    %   Z = MINUS(X,Y) substracts two TT/MPS tensors. The rank of the resulting
    %   tensor is the sum of the individual ranks.
    %
    %   See also PLUS, UMINUS.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    z = plus(x, uminus(y));
end