Description of norm
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > norm.m
norm
PURPOSE
NORM Norm of a TT/MPS tensor.
SYNOPSIS
function res = norm(x, safe)
DESCRIPTION
NORM Norm of a TT/MPS tensor.
   norm(X) computes the Frobenius norm of the TT/MPS tensor X.
   norm(X, SAFE) with SAFE=true computes the Frobenius norm of the TT/MPS tensor X
       with reorthogonalization to increase the accuracy
   See also INNERPROD
CROSS-REFERENCE INFORMATION
This function calls:
innerprod INNERPROD Inner product between two TT/MPS tensors.
norm NORM Norm of a TT/MPS tensor.
orthogonalize ORTHOGONALIZE Orthogonalize tensor.
innerprod INNERPROD Inner product between two TT/MPS tensors.
norm NORM Norm of a TT/MPS block-mu tensor.
orthogonalize ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
This function is called by:
PCA_stochastic Example of stochastic gradient algorithm in Manopt on a PCA problem.
dominant_invariant_subspace Returns an orthonormal basis of the dominant invariant p-subspace of A.
dominant_invariant_subspace_complex Returns a unitary basis of the dominant invariant p-subspace of A.
doubly_stochastic_denoising Find a doubly stochastic matrix closest to a given matrix, in Frobenius norm.
generalized_eigenvalue_computation Returns orthonormal basis of the dominant invariant p-subspace of B^-1 A.
generalized_procrustes Rotationally align clouds of points (generalized Procrustes problem)
low_rank_matrix_completion Given partial observation of a low rank matrix, attempts to complete it.
low_rank_tensor_completion Given partial observation of a low rank tensor, attempts to complete it.
low_rank_tensor_completion_TT Example file for the manifold encoded in fixedTTrankfactory.
low_rank_tensor_completion_embedded Given partial observation of a low rank tensor (possibly including noise),
radio_interferometric_calibration Returns the gain matrices of N stations with K receivers.
shapefit_smoothed ShapeFit formulation for sensor network localization from pair directions
sparse_pca Sparse principal component analysis based on optimization over Stiefel.
truncated_svd Returns an SVD decomposition of A truncated to rank p.
using_gpu Manopt example on how to use GPU with manifold factories that allow it.
using_gpu_AD Manopt example on how to use GPU to compute the egrad and the ehess via AD.
complexcirclefactory Returns a manifold struct to optimize over unit-modulus complex numbers.
realphasefactory Returns a manifold struct to optimize over phases of fft's of real signals
essentialfactory Manifold structure to optimize over the space of essential matrices.
essential_distMinAnglePair_discontinuityDistance
centeredmatrixfactory Linear manifold struct. for optimization over matrices with centered cols
euclideancomplexfactory Returns a manifold struct to optimize over complex matrices.
euclideanfactory Returns a manifold struct to optimize over real matrices.
euclideansparsefactory Returns a manifold struct to optimize over real matrices with given sparsity pattern.
shapefitfactory Linear manifold structure for optimization over the ShapeFit search space
skewsymmetricfactory Returns a manifold struct to optimize over k skew-symmetric matrices of size n
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
fixedrankembeddedfactory Manifold struct to optimize fixed-rank matrices w/ an embedded geometry.
fixedrankfactory_2factors Manifold of m-by-n matrices of rank k with balanced quotient geometry.
fixedrankfactory_2factors_preconditioned Manifold of m-by-n matrices of rank k with two factor quotient geometry.
grassmanncomplexfactory Returns a manifold struct to optimize over the set of subspaces in C^n.
grassmannfactory Returns a manifold struct to optimize over the space of vector subspaces.
grassmanngeneralizedfactory Returns a manifold struct of "scaled" vector subspaces.
hyperbolicfactory Factory for matrices whose columns live on the hyperbolic manifold
multinomialfactory Manifold of n-by-m column-stochastic matrices with positive entries.
obliquecomplexfactory Returns a manifold struct defining complex matrices w/ unit-norm columns.
obliquefactory Returns a manifold struct to optimize over matrices w/ unit-norm columns.
positivefactory Manifold of m-by-n matrices with positive entries; scale invariant metric
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
unitaryfactory Returns a manifold structure to optimize over unitary matrices.
spherecomplexfactory Returns a manifold struct to optimize over unit-norm complex matrices.
spherefactory Returns a manifold struct to optimize over unit-norm vectors or matrices.
spheresymmetricfactory Returns a manifold struct to optimize over unit-norm symmetric matrices.
stiefelcomplexfactory Returns a manifold struct. to optimize over complex orthonormal matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
stiefelgeneralizedfactory Returns a manifold structure of "scaled" orthonormal matrices.
stiefelstackedfactory Stiefel(k, d)^m, represented as matrices of size m*d-by-k.
elliptopefactory Manifold of n-by-n psd matrices of rank k with unit diagonal elements.
spectrahedronfactory Manifold of n-by-n symmetric positive semidefinite matrices of rank k
symfixedrankYYfactory Manifold of n-by-n symmetric positive semidefinite matrices of rank k.
TT_weingarten Weingarten map computation for the fixed TT-rank manifold.
TTeMPS
norm NORM Norm of a TT/MPS tensor.
TTeMPS_block
norm NORM Norm of a TT/MPS block-mu tensor.
TTeMPS_tangent_orth
completion Completion for Tensor train but without individual orthogonalization
completion_als ALS Completion
completion_orth RTTC: Riemannian Tensor Train Completion
completion_orth_lambda RTTC: Riemannian Tensor Train Completion
completion_rankincrease
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
increaseRank_mod Rank-1 gradient approximation to increase the rank.
RiemannLinsolve Riemannian approx. Newton for linear systems. For more information, we refer to the report
RiemannPrecondSteep TTeMPS Toolbox.
alsLinsolve TTeMPS Toolbox.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
check_precond_laplace TTeMPS Toolbox.
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
ex_completion_compare_als_riemann This example shows a simple comparison of two different algorithm for tensor completion:
ex_completion_rankadaptive Example script for RANK-ADAPTIVE TENSOR COMPLETION, see Algorithm RTTC described in
linearsystem_compare Example code for the algorithms described in
fixedTTrankfactory Manifold of tensors of fixed Tensor Train (TT) rank, embedded geometry
arc_lanczos Subproblem solver for ARC based on a Lanczos process.
minimize_cubic_newton Minimize a cubicly regularized quadratic via Newton root finding.
TRSgep Solves trust-region subproblem by a generalized eigenvalue problem.
checkmanifold Run a collection of tests on a manifold obtained from a manopt factory
checkretraction Check the order of agreement of a retraction with an exponential.
SOURCE CODE
function res = norm(x, safe)
    %NORM Norm of a TT/MPS tensor.
    %   norm(X) computes the Frobenius norm of the TT/MPS tensor X.
    %
    %   norm(X, SAFE) with SAFE=true computes the Frobenius norm of the TT/MPS tensor X
    %       with reorthogonalization to increase the accuracy
    %
    %   See also INNERPROD
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    if ~exist('safe','var')
        safe = true;
    end
    if safe
        x = orthogonalize(x, x.order );
        res = norm( x.U{end}(:) );
    else
        res = sqrt(innerprod( x, x ));
        if res < 1e-7
            x = orthogonalize(x, x.order );
            res = norm( x.U{end}(:) );
        end
    end
end