Description of orth_at
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > orth_at.m
orth_at
PURPOSE
ORTH_AT Orthogonalize single core.
SYNOPSIS
function [x, R] = orth_at(x, pos, dir, apply)
DESCRIPTION
ORTH_AT Orthogonalize single core.
   X = ORTH_AT( X, POS, 'LEFT') left-orthogonalizes the core at position POS
   and multiplies the corresponding R-factor with core POS+1. All other cores
   are untouched. The modified tensor is returned.
   X = ORTH_AT( X, POS, 'RIGHT') right-orthogonalizes the core at position POS
   and multiplies the corresponding R-factor with core POS-1. All other cores
   are untouched. The modified tensor is returned.
   See also ORTHOGONALIZE.
CROSS-REFERENCE INFORMATION
This function calls:
apply APPLY Application of TT/MPS operator to a TT/MPS tensor
apply APPLY Application of TT/MPS Laplace-like operator to a TT/MPS tensor
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
unfold UNFOLD Left/right-unfold a 3D array.
qr_unique Thin QR factorization ensuring diagonal of R is real, positive if possible.
This function is called by:
TTeMPS
left_orth_with_gauge LEFT_ORTH_WITH_GAUGE Left orthogonalization with storage of gauge matrices
orthogonalize ORTHOGONALIZE Orthogonalize tensor.
TTeMPS_block
completion_als ALS Completion
alsLinsolve TTeMPS Toolbox.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
SOURCE CODE
function [x, R] = orth_at(x, pos, dir, apply)
    %ORTH_AT Orthogonalize single core.
    %   X = ORTH_AT( X, POS, 'LEFT') left-orthogonalizes the core at position POS
    %   and multiplies the corresponding R-factor with core POS+1. All other cores
    %   are untouched. The modified tensor is returned.
    %
    %   X = ORTH_AT( X, POS, 'RIGHT') right-orthogonalizes the core at position POS
    %   and multiplies the corresponding R-factor with core POS-1. All other cores
    %   are untouched. The modified tensor is returned.
    %
    %   See also ORTHOGONALIZE.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    if ~exist('apply', 'var')
        apply = true;
    end
    sz = size(x.U{pos});
    if length(sz) == 2
        sz = [sz, 1];
    end
    if strcmpi(dir, 'left')
        [Q, R] = qr_unique(unfold(x.U{pos}, 'left'));
        x.U{pos} = reshape(Q, [sz(1), sz(2), size(Q, 2)]);
        if apply
            x.U{pos + 1} = tensorprod_ttemps(x.U{pos + 1}, R, 1);
        end
    elseif strcmpi(dir, 'right')
        % mind the transpose as we want to orthonormalize rows
        [Q, R] = qr_unique(unfold(x.U{pos}, 'right')');
        x.U{pos} = reshape(Q', [size(Q, 2), sz(2), sz(3)]);
        if apply
            x.U{pos - 1} = tensorprod_ttemps(x.U{pos - 1}, R, 3);
        end
    else
        error('Unknown direction specified. Choose either LEFT or RIGHT')
    end
end