Description of round
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > round.m
round
PURPOSE
ROUND Approximate TTeMPS tensor within a prescribed tolerance.
SYNOPSIS
function x = round(x, tol)
DESCRIPTION
ROUND Approximate TTeMPS tensor within a prescribed tolerance.
   X = ROUND( X, tol ) truncates the given TTeMPS tensor X to a
   lower rank such that the error is in order of tol.
CROSS-REFERENCE INFORMATION
This function calls:
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
trunc_singular REL_TRUNC_SINGULAR Helper routine to truncate singular values
unfold UNFOLD Left/right-unfold a 3D array.
This function is called by:
elliptope_SDP Solver for semidefinite programs (SDP's) with unit diagonal constraints.
elliptope_SDP_complex Solver for complex semidefinite programs (SDP's) with unit diagonal.
low_rank_tensor_completion Given partial observation of a low rank tensor, attempts to complete it.
low_rank_tensor_completion_TT Example file for the manifold encoded in fixedTTrankfactory.
low_rank_tensor_completion_embedded Given partial observation of a low rank tensor (possibly including noise),
realphasefactory Returns a manifold struct to optimize over phases of fft's of real signals
essentialfactory Manifold structure to optimize over the space of essential matrices.
TTeMPS_block
round ROUND Approximate TTeMPS tensor within a prescribed tolerance.
TTeMPS_op
round ROUND Approximate TTeMPS operator within a prescribed tolerance.
example TTeMPS Toolbox.
trs_gep Solves trust-region subproblem with TRSgep in a subspace of tangent space.
tangentorthobasis Returns an orthonormal basis of tangent vectors in the Manopt framework.
SOURCE CODE
function x = round(x, tol)
    %ROUND Approximate TTeMPS tensor within a prescribed tolerance.
    %   X = ROUND( X, tol ) truncates the given TTeMPS tensor X to a
    %   lower rank such that the error is in order of tol.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    sz = x.size;
    d = x.order;
    % Left-right procedure
    x = x.orthogonalize( d );
    right_rank = 1;
    for i = d:-1:2
        [U,S,V] = svd( unfold( x.U{i}, 'right'), 'econ' );
        r = trunc_singular( diag(S), tol, true );
        U = U(:,1:r);
        V = V(:,1:r);
        S = S(1:r,1:r);
        x.U{i} = reshape( V', [r, sz(i), right_rank] );
        x.U{i-1} = tensorprod_ttemps( x.U{i-1}, (U*S).', 3 );
        right_rank = r;
    end
end