Description of truncate
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > truncate.m
truncate
PURPOSE
TRUNCATE Truncate TTeMPS tensor to prescribed rank.
SYNOPSIS
function x = truncate(x, r)
DESCRIPTION
TRUNCATE Truncate TTeMPS tensor to prescribed rank.
   X = TRUNCATE( X, R ) truncates the given TTeMPS tensor X to rank R.
 The result is a right orthogonal TTeMPS.
CROSS-REFERENCE INFORMATION
This function calls:
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
unfold UNFOLD Left/right-unfold a 3D array.
This function is called by:
TTeMPS
TTeMPS_block
truncate ROUND Approximate TTeMPS tensor within a prescribed tolerance.
TTeMPS_tangent
TTeMPS_tangent_orth
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
example TTeMPS Toolbox.
SOURCE CODE
function x = truncate(x, r)
    %TRUNCATE Truncate TTeMPS tensor to prescribed rank.
    %   X = TRUNCATE( X, R ) truncates the given TTeMPS tensor X to rank R.
    % The result is a right orthogonal TTeMPS.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    % Left-right procedure
    x = x.orthogonalize( x.order );
    for i = x.order:-1:2
        [U,S,V] = svd( unfold( x.U{i}, 'right'), 'econ');
        s = min( r(i), length(S));
        U = U(:,1:s);
        V = V(:,1:s);
        S = S(1:s,1:s);
        x.U{i} = reshape( V', [s, x.size(i), x.rank(i+1)] );
        x.U{i-1} = tensorprod_ttemps( x.U{i-1}, (U*S)', 3 );
    end
end