Description of TTeMPS
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS > TTeMPS.m
TTeMPS
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
TTeMPS
TTeMPS_to_TT TTeMPS_to_TT Convert to TT Toolbox format.
cat CAT concatenation of two TT/MPS tensors.
contract CONTRACT Contraction of two TT/MPS tensors.
disp DISP Display TT/MPS tensor.
display DISP Display TT/MPS tensor as a tensor network
from_array FROM_ARRAY Approximate full array by TTeMPS tensor of prescribed rank
full FULL Convert TTeMPS tensor to full array
gauge_matrices GAUGE_MATRICES Right and left orthogonalization with storage of gauge matrices
hadamard HADAMARD Hadamard product of two TT/MPS tensors.
innerprod INNERPROD Inner product between two TT/MPS tensors.
minus MINUS Substraction of two TT/MPS tensors.
mtimes MINUS Multiplication of TT/MPS tensor by scalar.
norm NORM Norm of a TT/MPS tensor.
orth_at ORTH_AT Orthogonalize single core.
orthogonalize ORTHOGONALIZE Orthogonalize tensor.
plus PLUS Addition of two TT/MPS tensors.
splitcore SPLITCORE Merging of two cores of a TT/MPS tensor.
truncate TRUNCATE Truncate TTeMPS tensor to prescribed rank.
uminus UMINUS Unary minus.
uplus UPLUS Unary plus.
disp DISP Display TT/MPS block-mu tensor.
display DISP Display TT/MPS tensor as a tensor network
full FULL Convert TTeMPS tensor to full array
innerprod INNERPROD Inner product between two TT/MPS tensors.
minus MINUS Substraction of two TT/MPS block-mu tensors.
mtimes MINUS Multiplication of TT/MPS block tensor by scalar or vector
norm NORM Norm of a TT/MPS block-mu tensor.
orthogonalize ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
plus PLUS Addition of two TT/MPS block-mu tensors.
truncate ROUND Approximate TTeMPS tensor within a prescribed tolerance.
uminus UMINUS Unary minus.
uplus UPLUS Unary plus.
apply APPLY Application of TT/MPS operator to a TT/MPS tensor
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS operator.
disp DISP Display TT/MPS operator.
display DISPLAY Display TT/MPS tensor as a tensor network
full FULL Convert TTeMPS_op operator to full array
mtimes MINUS Multiplication of TT/MPS operator by scalar.
plus PLUS Addition of two TT/MPS operators.
apply APPLY Application of TT/MPS Laplace-like operator to a TT/MPS tensor
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS Laplace operator.
disp DISP Display TT/MPS operator.
display DISP Display TT/MPS tensor as a tensor network
mtimes MINUS Multiplication of TT/MPS Laplace operator by scalar.
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
This function is called by:
TTeMPS
cat CAT concatenation of two TT/MPS tensors.
from_array FROM_ARRAY Approximate full array by TTeMPS tensor of prescribed rank
hadamard HADAMARD Hadamard product of two TT/MPS tensors.
mergecore MERGECORE Merging of two cores of a TT/MPS tensor.
plus PLUS Addition of two TT/MPS tensors.
splitcore SPLITCORE Merging of two cores of a TT/MPS tensor.
TTeMPS_block
TTeMPS_op_to_TTeMPS TTeMPS_op_to_TTeMPS Convert to TT Toolbox matrix format.
apply APPLY Application of TT/MPS operator to a TT/MPS tensor
round ROUND Approximate TTeMPS operator within a prescribed tolerance.
apply APPLY Application of TT/MPS Laplace-like operator to a TT/MPS tensor
TTeMPS_tangent
TTeMPS_tangent_orth
TT_to_TTeMPS TT_to_TTeMPS Convert from TT Toolbox format.
TTeMPS_rand TTEMPS_RAND Create random TTeMPS tensor
TTeMPS_randn TTEMPS_RANDN Create random TTeMPS tensor
precond_laplace_noSaddle TTeMPS Toolbox.
install_mex Install helper for mex functions
newton_potential
SUBFUNCTIONS
function rank_ = get.rank(x)
function size_ = get.size(x)
function order_ = get.order(x)
function x = TTeMPS(varargin)
SOURCE CODE
classdef TTeMPS
% TTeMPS
%
%   A MATLAB class for representing and manipulating tensors
%   in the TT/MPS format.
%
%   TTeMPS Toolbox.
%   Michael Steinlechner, 2013-2016
%   Questions and contact: michael.steinlechner@epfl.ch
%   BSD 2-clause license, see LICENSE.txt
properties(SetAccess = public, GetAccess = public)
    U           % core tensors
end
% Dependent properties
properties(Dependent = true, SetAccess = private, GetAccess = public)
    rank
    order
    size
end
% Get methods for dependent properties (computed on-the-fly)
methods
    function rank_ = get.rank(x)
        rank_ = cellfun( @(x) size(x,1), x.U);
        rank_ = [rank_, size(x.U{end},3)];
    end
    function size_ = get.size(x)
        size_ = cellfun( @(y) size(y,2), x.U);
    end
    function order_ = get.order(x)
        order_ = length( x.U );
    end
end
methods(Access = public)
    function x = TTeMPS(varargin)
    %TTEMPS Construct a tensor in TT/MPS format and return TTeMPS object.
    %
    %   X = TTEMPS() creates a zero TT/MPS tensor
    %
    %   X = TTEMPS(CORES) creates a TT/MPS tensor with core tensors C taken
    %   from the cell array CORES
    %
        % Default constructor
        if (nargin == 0)
            x = TTeMPS( {0 0 0} );
            return;
        elseif (nargin == 1)
            x.U = varargin{1};
            return;
        else
            error('Invalid number of arguments.')
        end
    end
    % Other public functions
    y = full( x );
    [x, r] = orth_at( x, pos, dir, apply );
    x = orthogonalize( x, pos );
    res = innerprod( x, y, dir, upto, storeParts );
    res = norm( x, safe );
    res = contract( x, y, idx );
    x = truncate( x, r );
    x = uminus( x );
    x = uplus( x );
    z = plus( x, y );
    z = minus( x, y );
    x = mtimes( a, x );
    z = hadamard( x, y, idx );
    y = mergecores( x, idx );
    y = splitcore( x, idx, nL, nR, tol );
    z = hadamard_division( x, y, idx );
    z = TTeMPS_to_TT( x );
    z = cat( mu, x, y );
    [xl,xr,g] = gauge_matrices( x );
    disp( x, name );
    display( x );
end
methods(Static, Access = public)
    x = from_array( A, opts );
end
methods(Static, Access = private)
    x = subsref_mex( r, n, ind , C);
end
end