Description of disp
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS_block > disp.m
disp
PURPOSE
DISP Display TT/MPS block-mu tensor.
SYNOPSIS
function disp(x, name)
DESCRIPTION
DISP Display TT/MPS block-mu tensor.
   disp(X) displays the TT/MPS block-mu tensor X as a tensor network.
CROSS-REFERENCE INFORMATION
This function calls:
disp DISP Display TT/MPS tensor.
disp DISP Display TT/MPS block-mu tensor.
disp DISP Display TT/MPS operator.
disp DISP Display TT/MPS operator.
This function is called by:
dominant_invariant_subspace Returns an orthonormal basis of the dominant invariant p-subspace of A.
dominant_invariant_subspace_complex Returns a unitary basis of the dominant invariant p-subspace of A.
low_rank_dist_completion Perform low-rank distance matrix completion w/ automatic rank detection.
low_rank_matrix_completion Given partial observation of a low rank matrix, attempts to complete it.
low_rank_tensor_completion Given partial observation of a low rank tensor, attempts to complete it.
low_rank_tensor_completion_TT Example file for the manifold encoded in fixedTTrankfactory.
run_all_examples
essential_distMinAnglePair_ftFromQ
TTeMPS
disp DISP Display TT/MPS tensor.
display DISP Display TT/MPS tensor as a tensor network
TTeMPS_block
disp DISP Display TT/MPS block-mu tensor.
display DISP Display TT/MPS tensor as a tensor network
shift TTeMPS Toolbox.
TTeMPS_op
disp DISP Display TT/MPS operator.
display DISPLAY Display TT/MPS tensor as a tensor network
TTeMPS_op_laplace
disp DISP Display TT/MPS operator.
display DISP Display TT/MPS tensor as a tensor network
completion Completion for Tensor train but without individual orthogonalization
completion_als ALS Completion
completion_orth RTTC: Riemannian Tensor Train Completion
completion_orth_lambda RTTC: Riemannian Tensor Train Completion
completion_rankincrease
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
RiemannLinsolve Riemannian approx. Newton for linear systems. For more information, we refer to the report
alsLinsolve TTeMPS Toolbox.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
solvePrecond_noSaddle TTeMPS Toolbox.
example TTeMPS Toolbox.
linearsystem_compare Example code for the algorithms described in
install TTeMPS Toolbox.
install_mex Install helper for mex functions
trustregions Riemannian trust-regions solver for optimization on manifolds.
SOURCE CODE
function disp(x, name)
    %DISP Display TT/MPS block-mu tensor.
    %   disp(X) displays the TT/MPS block-mu tensor X as a tensor network.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    if (nargin < 2 || ~ischar(name))
      name = inputname(1);
    end
    disp([name, ' is a TT/MPS block-', num2str(x.mu), ' (with block size ', num2str(x.p), ') tensor of order ', num2str(x.order), ...
                        ' with size (', num2str(x.size), ...
                        ') and ranks (', num2str(x.rank), ')']);
    disp('');
    row1 = '';
    row2 = '';
    row3 = '';
    row4 = '';
    for i=1:x.order
        if i == x.mu
            row1 = [row1, sprintf('      p=%i    ', x.p)];
        else
            row1 = [row1, '            '];
        end
        row2 = [row2, sprintf('%3i--(U%2i)--', x.rank(i), i)];
        row3 = [row3, '       |    '];
        row4 = [row4, sprintf('     %3i    ', x.size(i))];
    end
    row2 = [row2, sprintf( '%3i', x.rank(end) )];
    disp(row1)
    disp(row2)
    disp(row3)
    disp(row4)
end