Description of full
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS_block > full.m
full
PURPOSE
FULL Convert TTeMPS tensor to full array
SYNOPSIS
function y = full(x)
DESCRIPTION
FULL Convert TTeMPS tensor to full array
   X = FULL(X) converts the TTeMPS tensor X to a (X.order)-dimensional full array of size
   X.size(1) x X.size(2) x ... x X.size(X.order)
    Use with care! Result can easily exceed available memory.
   See also SUBSREF.
CROSS-REFERENCE INFORMATION
This function calls:
unfold UNFOLD Left/right-unfold a 3D array.
This function is called by:
low_rank_tensor_completion_embedded Given partial observation of a low rank tensor (possibly including noise),
shapefit_smoothed ShapeFit formulation for sensor network localization from pair directions
TT_weingarten Weingarten map computation for the fixed TT-rank manifold.
TTeMPS
subsref SUBSREF Subscripted reference for TTeMPS.
TTeMPS_block
TTeMPS_op
full FULL Convert TTeMPS_op operator to full array
TTeMPS_op_laplace
TTeMPS_op_laplace_to_TTeMPS_op TTeMPS_op_laplace_to_TTeMPS Convert to TT_op_laplace to TTeMPS_op format.
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS Laplace operator.
TTeMPS_tangent
TTeMPS_tangent_orth
TTeMPS_op_NN
TTeMPS_op_NN_hermite
anisotropicdiffusion
newton_potential
fixedTTrankfactory Manifold of tensors of fixed Tensor Train (TT) rank, embedded geometry
SOURCE CODE
function y = full(x)
    %FULL Convert TTeMPS tensor to full array
    %   X = FULL(X) converts the TTeMPS tensor X to a (X.order)-dimensional full array of size
    %   X.size(1) x X.size(2) x ... x X.size(X.order)
    %
    %    Use with care! Result can easily exceed available memory.
    %
    %   See also SUBSREF.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    y = x.U{1};
    y = reshape( y, [ x.size(1), x.rank(2) ]);
    for i = 2:x.order
        U_temp = unfold( x.U{i}, 'right');
        y = y * U_temp;
        y = reshape( y, [ prod(x.size(1:i)), x.rank(i+1) ]);
    end
    y = reshape( y, x.size );
end