Description of innerprod
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS_block > innerprod.m
innerprod
PURPOSE
INNERPROD Inner product between two TT/MPS tensors.
SYNOPSIS
function res = innerprod(x, y, dir, upto)
DESCRIPTION
INNERPROD Inner product between two TT/MPS tensors.
   innerprod(X,Y) computes the inner product between the TT/MPS tensors X and Y.
   Assumes that the first rank of both tensors, X.rank(1) and Y.rank(1), is 1.
   The last rank may be different from 1, resulting in a matrix of size
   [X.rank(end), Y.rank(end)].
   See also NORM
CROSS-REFERENCE INFORMATION
This function calls:
tensorprod_ttemps TENSORPROD_TTEMPS Tensor-times-Matrix product.
unfold UNFOLD Left/right-unfold a 3D array.
This function is called by:
fixedranktensorembeddedfactory Manifold of tensors with fixed multilinear rank in Tucker format
TTeMPS
contract CONTRACT Contraction of two TT/MPS tensors.
norm NORM Norm of a TT/MPS tensor.
TTeMPS_block
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS operator.
constr_precond_inner TTeMPS Toolbox.
contract CONTRACT Contraction of two TT/MPS tensors with inner TT/MPS Laplace operator.
TTeMPS_tangent
TTeMPS_tangent_orth
completion Completion for Tensor train but without individual orthogonalization
completion_orth RTTC: Riemannian Tensor Train Completion
completion_orth_lambda RTTC: Riemannian Tensor Train Completion
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
RiemannLinsolve Riemannian approx. Newton for linear systems. For more information, we refer to the report
RiemannPrecondSteep TTeMPS Toolbox.
alsLinsolve TTeMPS Toolbox.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
precond_laplace_noorth TTeMPS Toolbox.
precond_laplace_overlapGS TTeMPS Toolbox.
precond_laplace_overlapJacobi TTeMPS Toolbox.
precond_rankOne TTeMPS Toolbox.
example TTeMPS Toolbox.
linearsystem_compare Example code for the algorithms described in
TTeMPS_op_NN
TTeMPS_op_NN_hermite
anisotropicdiffusion
newton_potential
fixedTTrankfactory Manifold of tensors of fixed Tensor Train (TT) rank, embedded geometry
SOURCE CODE
function res = innerprod(x, y, dir, upto)
    %INNERPROD Inner product between two TT/MPS tensors.
    %   innerprod(X,Y) computes the inner product between the TT/MPS tensors X and Y.
    %   Assumes that the first rank of both tensors, X.rank(1) and Y.rank(1), is 1.
    %   The last rank may be different from 1, resulting in a matrix of size
    %   [X.rank(end), Y.rank(end)].
    %
    %   See also NORM
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    if ~exist( 'dir', 'var' )
        dir = 'LR';
    end
    if ~exist( 'upto', 'var' )
        if strcmpi( dir, 'LR')
            upto = x.order;
        else
            upto = 1;
        end
    end
    % Left-to-Right procedure
    if strcmpi( dir, 'LR')
        res = unfold( x.U{1}, 'left')' * unfold( y.U{1}, 'left');
        for i = 2:upto
            tmp = tensorprod_ttemps( x.U{i}, res', 1);
            res = unfold( tmp, 'left')' * unfold( y.U{i}, 'left');
        end
    % Right-to-Left procedure
    elseif strcmpi( dir, 'RL')
        d = x.order;
        res = conj(unfold( x.U{d}, 'right')) * unfold( y.U{d}, 'right').';
        for i = d-1:-1:upto
            tmp = tensorprod_ttemps( x.U{i}, res', 3);
            res = conj(unfold( tmp, 'right')) * unfold( y.U{i}, 'right').';
        end
    else
        error('Unknown direction specified. Choose either LR (default) or RL')
    end
end