Description of orthogonalize
Home > manopt > manifolds > ttfixedrank > TTeMPS_1.1 > @TTeMPS_block > orthogonalize.m
orthogonalize
PURPOSE
ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
SYNOPSIS
function res = orthogonalize(x)
DESCRIPTION
ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
   X = ORTHOGONALIZE( X ) orthogonalizes all cores of the TTeMPS_block tensor X
   except the supercore at position X.MU. Cores 1...X.MU-1 are left-, cores X.MU+1...end
   are right-orthogonalized.
CROSS-REFERENCE INFORMATION
This function calls:
orthogonalize ORTHOGONALIZE Orthogonalize tensor.
orthogonalize ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
orthogonalize Orthonormalizes a basis of tangent vectors in the Manopt framework.
This function is called by:
low_rank_tensor_completion_TT Example file for the manifold encoded in fixedTTrankfactory.
TTeMPS
gauge_matrices GAUGE_MATRICES Right and left orthogonalization with storage of gauge matrices
norm NORM Norm of a TT/MPS tensor.
norm NORM Norm of a TT/MPS block-mu tensor.
orthogonalize ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
TTeMPS_tangent_orth
completion Completion for Tensor train but without individual orthogonalization
completion_als ALS Completion
completion_orth RTTC: Riemannian Tensor Train Completion
completion_orth_lambda RTTC: Riemannian Tensor Train Completion
completion_rankincrease
amen_eigenvalue AMEN_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
block_eigenvalue BLOCK_EIGENVALUE Calculate p smallest eigenvalues of a TTeMPS operator
increaseRank_mod Rank-1 gradient approximation to increase the rank.
alsLinsolve TTeMPS Toolbox.
alsLinsolve_fast TTeMPS Toolbox.
alsLinsolve_rankOne TTeMPS Toolbox.
amen TTeMPS Toolbox.
amen_fast TTeMPS Toolbox.
construct_initial_guess TTeMPS Toolbox.
construct_initial_guess_rankOne TTeMPS Toolbox.
ex_completion_compare_als_riemann This example shows a simple comparison of two different algorithm for tensor completion:
ex_completion_rankadaptive Example script for RANK-ADAPTIVE TENSOR COMPLETION, see Algorithm RTTC described in
example TTeMPS Toolbox.
fixedTTrankfactory Manifold of tensors of fixed Tensor Train (TT) rank, embedded geometry
orthogonalizetwice Orthonormalizes a basis of tangent vectors twice for increased accuracy.
tangentorthobasis Returns an orthonormal basis of tangent vectors in the Manopt framework.
SOURCE CODE
function res = orthogonalize(x)
    %ORTHOGONALIZE Orthogonalize TT/MPS Block-mu tensor.
    %   X = ORTHOGONALIZE( X ) orthogonalizes all cores of the TTeMPS_block tensor X
    %   except the supercore at position X.MU. Cores 1...X.MU-1 are left-, cores X.MU+1...end
    %   are right-orthogonalized.
    %   TTeMPS Toolbox.
    %   Michael Steinlechner, 2013-2016
    %   Questions and contact: michael.steinlechner@epfl.ch
    %   BSD 2-clause license, see LICENSE.txt
    y = TTeMPS_block_to_TTeMPS( x );
    yorth = orthogonalize(y, x.mu );
    res = TTeMPS_block.TTeMPS_to_TTeMPS_block( yorth, x.mu, x.p );
    %tmp = permute( y.U{mu}, [1 2 4 3] );
    %tmp = reshape( tmp, [x.rank(mu), x.size(mu)*x.p, x.rank(mu+1)];
    %X = TTeMPS({x.U{1:mu-1}, tmp, x.U{1:mu+1} );
    % left orthogonalization till x.mu (from left)
    %for i = 1:x.mu-1
    %    [Q,R] = qr( unfold( x.U{i}, 'left' ), 0);
    %    x.U{pos} = reshape( Q, [x.rank(pos), x.size(pos), size(Q,2)] );
    %    if apply
    %        x.U{pos+1} = tensorprod_ttemps( x.U{pos+1}, R, 1);
    %    end
    %end
    %% right orthogonalization till x.mu (from right)
    %for i = x.order:-1:x.mu+1
    %
    %end
end