Description of cprod
Home > manopt > autodiff > functions_AD > cprod.m
cprod
PURPOSE
Computes the product of A and B
SYNOPSIS
function prodAB = cprod(A,B)
DESCRIPTION
 Computes the product of A and B
 function prodAB = cprod(A,B)
 Returns the product of A and B. This function can be seen as A*B but is
 compatible with dlarrays and structs with fields real and imag.
 See also: manoptADhelp
CROSS-REFERENCE INFORMATION
This function calls:
iscstruct
This function is called by:
complex_example_AD A basic example that shows how to define the cost funtion for
complextest_AD1 Test AD for a complex optimization problem on a product manifold (struct)
complextest_AD2 Test AD for a complex optimization problem on a power manifold (cell)
complextest_AD3 Test AD for a complex optimization problem on a manifold which is stored
SOURCE CODE
function prodAB = cprod(A,B)
% Computes the product of A and B
%
% function prodAB = cprod(A,B)
%
% Returns the product of A and B. This function can be seen as A*B but is
% compatible with dlarrays and structs with fields real and imag.
%
% See also: manoptADhelp
% This file is part of Manopt: www.manopt.org.
% Original author: Xiaowen Jiang, July. 31, 2021.
% Contributors: Nicolas Boumal
% Change log:
    if isnumeric(A) && iscstruct(B)
        realA = real(A);
        imagA = imag(A);
        prodAB.real = realA*B.real - imagA*B.imag;
        prodAB.imag = realA*B.imag + imagA*B.real;
    elseif iscstruct(A) && isnumeric(B)
        realB = real(B);
        imagB = imag(B);
        prodAB.real = A.real*realB - A.imag*imagB;
        prodAB.imag = A.real*imagB + A.imag*realB;
    elseif isnumeric(A) && isnumeric(B)
        prodAB = A*B;
    elseif iscstruct(A) && iscstruct(B)
        prodAB.real = A.real*B.real - A.imag*B.imag;
        prodAB.imag = A.real*B.imag + A.imag*B.real;
    else
        ME = MException('cprod:inputError', ...
                        'Input does not have the expected format.');
        throw(ME);
    end
end