Description of creal
Home > manopt > autodiff > functions_AD > creal.m
creal
PURPOSE
Extracts the real part of x
SYNOPSIS
function Xreal = creal(X)
DESCRIPTION
 Extracts the real part of x
 function Xreal = creal(X)
 Returns the real part of x. The input can be either a numeric array
 or a struct with fields real and imag.
 See also: manoptADhelp
CROSS-REFERENCE INFORMATION
This function calls:
iscstruct
This function is called by:
autograd Apply automatic differentiation to computing the Euclidean gradient
complex_example_AD A basic example that shows how to define the cost funtion for
complextest_AD1 Test AD for a complex optimization problem on a product manifold (struct)
complextest_AD2 Test AD for a complex optimization problem on a power manifold (cell)
complextest_AD3 Test AD for a complex optimization problem on a manifold which is stored
ehesscompute Computes the Euclidean Hessian of the cost function at x along xdot via AD.
cinnerprodgeneral Computes the Euclidean inner product between x and y in the complex case
SOURCE CODE
function Xreal = creal(X)
% Extracts the real part of x
%
% function Xreal = creal(X)
%
% Returns the real part of x. The input can be either a numeric array
% or a struct with fields real and imag.
%
% See also: manoptADhelp
% This file is part of Manopt: www.manopt.org.
% Original author: Xiaowen Jiang, July. 31, 2021.
% Contributors: Nicolas Boumal
% Change log:
    if iscstruct(X)
        Xreal = X.real;
    elseif isnumeric(X)
        Xreal = real(X);
    else
        ME = MException('creal:inputError', ...
                        'Input does not have the expected format.');
        throw(ME);
    end
end