Description of iscstruct
Home > manopt > autodiff > functions_AD > iscstruct.m
iscstruct
PURPOSE
SYNOPSIS
function flag = iscstruct(A)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
autograd Apply automatic differentiation to computing the Euclidean gradient
ehesscompute Computes the Euclidean Hessian of the cost function at x along xdot via AD.
cconj Computes the complex conjugate of x
cdiag Extracts the diagonal elements of A.
cdottimes Computes the element-wise multiplication between A and B
cmat2col Converts X into a column vector
cminus Computes the difference of A and B
cnormfro Computes the Frobenius norm of X
cnormsqfro Computes the squared Frobenius norm of X
cplus Computes the sum of A and B
cprod Computes the product of A and B
creal Extracts the real part of x
crepmat Replicates an array.
creshape Reshapes X.
ctrace Computes the sum of diagonal elements of A.
ctransp Computes the conjugate-transpose of X
ctril Extracts the lower triangular part of X.
ctriu Extracts the upper triangular part of X.
tocstruct
SOURCE CODE
function flag = iscstruct(A)
    flag = ( isstruct(A) && isfield(A, 'real') && isfield(A, 'imag') );
end