Description of tocstruct
Home > manopt > autodiff > functions_AD > tocstruct.m
tocstruct
PURPOSE
SYNOPSIS
function B = tocstruct(A)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
iscstruct
This function is called by:
cdottimes Computes the element-wise multiplication between A and B
cmultiscale Multiplies the 2D slices in a 3D array by individual scalars.
SOURCE CODE
function B = tocstruct(A)
    if iscstruct(A)
        B = A;
    elseif isnumeric(A)
        B.real = real(A);
        B.imag = imag(A);
    else
        error('Input does not have the expected format.');
    end
end