Description of multisym
Home > manopt > tools > multisym.m
multisym
PURPOSE
Returns the symmetric parts of the matrices in a 3D array
SYNOPSIS
function Y = multisym(X)
DESCRIPTION
 Returns the symmetric parts of the matrices in a 3D array
 function Y = multisym(X)
 Y is a 3D array the same size as X. Each slice Y(:, :, i) is the
 symmetric part of the slice X(:, :, i), that is,
   Y(:, :, i) = .5*(X(:, :, i) + X(:, :, i).')
 Note that we do not take complex conjugates. For this, see multiherm.
 See also: multiherm multiskew multiskewh multiprod multitransp multiscale
CROSS-REFERENCE INFORMATION
This function calls:
multitransp Transpose the matrix slices of an N-D array (no complex conjugate)
This function is called by:
essentialfactory Manifold structure to optimize over the space of essential matrices.
symmetricfactory Returns a manifold struct to optimize over k symmetric matrices of size n
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
stiefelstackedfactory Stiefel(k, d)^m, represented as matrices of size m*d-by-k.
SOURCE CODE
function Y = multisym(X)
% Returns the symmetric parts of the matrices in a 3D array
%
% function Y = multisym(X)
%
% Y is a 3D array the same size as X. Each slice Y(:, :, i) is the
% symmetric part of the slice X(:, :, i), that is,
%
%   Y(:, :, i) = .5*(X(:, :, i) + X(:, :, i).')
%
% Note that we do not take complex conjugates. For this, see multiherm.
%
% See also: multiherm multiskew multiskewh multiprod multitransp multiscale
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Jan. 31, 2013.
% Contributors:
% Change log:
    Y = .5*(X + multitransp(X));
end