Description of multiprod
Home > manopt > tools > multiprod.m
multiprod
PURPOSE
Matrix multiply 2-D slices of N-D arrays
SYNOPSIS
function C = multiprod(A, B, unused1, unused2) %#ok
DESCRIPTION
 Matrix multiply 2-D slices of N-D arrays
 function C = multiprod(A, B)
 If A, B are two 3-D arrays of compatible sizes, then C is a 3-D array
 such that
     C(:, :, i) = A(:, :, i) * B(:, :, i)
 for each i. Arrays have compatible sizes if the above is well defined.
 If A, B are two N-D arrays of compatible sizes, then C is an N-D array
 such that
     C(:, :, i, j, k, ...) = A(:, :, i, j, k, ...) * B(:, :, i, j, k, ...)
 for each i, j, k...
 This function is just a wrapper for pagemtimes, with a fallback call to
 multiprod_legacy in case pagemtimes is not available.
 If pagemtimes is available, it is better to call it directly. This is
 especially true if multiprod is called in conjunction with multitransp,
 as pagemtimes allows for both to be done in one function call.
 See also: multitransp multihconj multiscale multiskew multiskewh multitrace
CROSS-REFERENCE INFORMATION
This function calls:
multiprod_legacy Multiplying 1-D or 2-D subarrays contained in two N-D arrays.
This function is called by:
essential_svd Sample solution of an optimization problem on the essential manifold.
generalized_procrustes Rotationally align clouds of points (generalized Procrustes problem)
robust_pca Computes a robust version of PCA (principal component analysis) on data.
essential_costE2cost Cost evaluation at X given function handle in the Essential matrix E.
essential_egradE2egrad Converts the gradient in essential matrix E to the gradient in X.
essential_ehessE2ehess Converts the Hessian in essential matrix E to the Hessian in X.
essentialfactory Manifold structure to optimize over the space of essential matrices.
grassmanncomplexfactory Returns a manifold struct to optimize over the set of subspaces in C^n.
grassmannfactory Returns a manifold struct to optimize over the space of vector subspaces.
rotationsfactory Returns a manifold structure to optimize over rotation matrices.
unitaryfactory Returns a manifold structure to optimize over unitary matrices.
stiefelcomplexfactory Returns a manifold struct. to optimize over complex orthonormal matrices.
stiefelfactory Returns a manifold structure to optimize over orthonormal matrices.
stiefelstackedfactory Stiefel(k, d)^m, represented as matrices of size m*d-by-k.
SOURCE CODE
function C = multiprod(A, B, unused1, unused2) %#ok<INUSD>
% Matrix multiply 2-D slices of N-D arrays
%
% function C = multiprod(A, B)
%
% If A, B are two 3-D arrays of compatible sizes, then C is a 3-D array
% such that
%
%     C(:, :, i) = A(:, :, i) * B(:, :, i)
%
% for each i. Arrays have compatible sizes if the above is well defined.
%
% If A, B are two N-D arrays of compatible sizes, then C is an N-D array
% such that
%
%     C(:, :, i, j, k, ...) = A(:, :, i, j, k, ...) * B(:, :, i, j, k, ...)
%
% for each i, j, k...
%
% This function is just a wrapper for pagemtimes, with a fallback call to
% multiprod_legacy in case pagemtimes is not available.
% If pagemtimes is available, it is better to call it directly. This is
% especially true if multiprod is called in conjunction with multitransp,
% as pagemtimes allows for both to be done in one function call.
%
% See also: multitransp multihconj multiscale multiskew multiskewh multitrace
% This file is part of Manopt: www.manopt.org.
% Original author: Nicolas Boumal, Aug. 12, 2021.
% Contributors: Xiaowen Jiang
% Change log:
%
%   Aug. 12, 2021 (NB):
%       Matlab R2020b introduced a built-in function pagemtimes which does
%       essentially everything we ever needed to do with multiprod in
%       Manopt, and is much faster. It also has the advantage of being
%       compatible with dlarray, necessary for automatic differentiation.
%       Accordingly, multiprod became a wrapper for pagemtimes, and the old
%       code for multiprod remains available as multiprod_legacy.
    assert(nargin == 2, ...
           'The new multiprod only takes two inputs. Check multiprod_legacy.');
    if exist('pagemtimes', 'builtin') % Added to Matlab R2020b
        C = pagemtimes(A, B);
    else
    %   warning('manopt:multi', ...
    %          ['Matlab R2020b introduced pagemtimes, faster than multiprod.\n' ...
    %           'Calling the old code multiprod_legacy instead.\n' ...
    %           'To disable this warning: warning(''off'', ''manopt:multi'')']);
        C = multiprod_legacy(A, B);
    end
end